PRAGMA foreign_keys = OFF;
CREATE TABLE tblLeague (
League VARCHAR(4) NOT NULL PRIMARY KEY,
DH BOOLEAN NOT NULL
);

CREATE TABLE tblDivision(
Division VARCHAR(4) NOT NULL PRIMARY KEY,
League VARCHAR(4) NOT NULL,
FOREIGN KEY (League) REFERENCES tblLeague(League)
);

CREATE TABLE tblSponsor(
SponsorID INTEGER PRIMARY KEY AUTOINCREMENT,
SponsorName VARCHAR(24) NOT NULL UNIQUE,
Street VARCHAR(36) NOT NULL,
City VARCHAR(24) NOT NULL,
Province VARCHAR(2) NOT NULL,
Postal VARCHAR(6) NOT NULL,
Country VARCHAR(2) NOT NULL
);

CREATE TABLE tblPosition(
Position VARCHAR(16) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE tblStadium(
StadiumID INTEGER PRIMARY KEY AUTOINCREMENT,
StadiumName VARCHAR(36) NOT NULL,
Street VARCHAR(36) NOT NULL,
City VARCHAR(24) NOT NULL,
Province VARCHAR(2) NOT NULL,
Postal VARCHAR(6) NOT NULL,
Country VARCHAR(2) NOT NULL,
Seats INTEGER NOT NULL,
Indoor BOOLEAN NOT NULL
);

CREATE TABLE tblPlayer(
PlayerID INTEGER PRIMARY KEY AUTOINCREMENT,
First VARCHAR(24) NOT NULL,
Last VARCHAR(24) NOT NULL,
DOB DATE NOT NULL,
Team INT NOT NULL,
Position VARCHAR(18),
Injury BOOLEAN,
HandDominance VARCHAR(1) NOT NULL,
Nationality VARCHAR(3) NOT NULL,
Hometown VARCHAR(24) NOT NULL,
BattingAVG INTEGER(1000) NOT NULL,
FOREIGN KEY (Team) REFERENCES tblTeam(TeamID),
FOREIGN KEY (Position) REFERENCES tblPosition(Position)
);

CREATE TABLE tblStaff(
StaffID INTEGER PRIMARY KEY AUTOINCREMENT,
First VARCHAR(24) NOT NULL,
Last VARCHAR(24) NOT NULL,
DOB DATE NOT NULL,
Role VARCHAR(24) NOT NULL,
Stadium INTEGER NOT NULL,
FOREIGN KEY (Stadium) REFERENCES tblStadium(StadiumID)
);

CREATE TABLE tblTeam(
TeamID INTEGER PRIMARY KEY AUTOINCREMENT,
Team VARCHAR(24) NOT NULL,
Stadium INTEGER NOT NULL,
Division VARCHAR NOT NULL,
Sponsor INTEGER,
FOREIGN KEY (Stadium) REFERENCES tblStadium(StadiumID),
FOREIGN KEY (Division) REFERENCES tblDivision(Division),
FOREIGN KEY (Sponsor) REFERENCES tblSponsor(SponsorID)
);

CREATE TABLE tblLeaderboard(
Team INTEGER NOT NULL UNIQUE,
Playoff BOOLEAN NOT NULL,
Wins INTEGER,
Losses INTEGER,
FOREIGN KEY (Team) REFERENCES tblTeam(TeamID)
);